name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.changes.outputs.backend }}
      frontend: ${{ steps.changes.outputs.frontend }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for changes in backend or frontend
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'

  deploy_backend:
    needs: check_changes
    if: needs.check_changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Backend
        uses: digitalocean/app_action/deploy@v2
        with:
          app_id: ${{ secrets.DO_BACKEND_APP_ID }}
          token: ${{ secrets.DO_API_KEY }}

  deploy_frontend:
    needs: check_changes
    if: needs.check_changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Frontend
        uses: digitalocean/app_action/deploy@v2
        with:
          app_id: ${{ secrets.DO_FRONTEND_APP_ID }}
          token: ${{ secrets.DO_API_KEY }}
          
