name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.changes.outputs.backend }}
      frontend: ${{ steps.changes.outputs.frontend }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for changes in backend or frontend
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'

  deploy_backend:
    runs-on: ubuntu-latest
    needs: check_changes
    if: needs.check_changes.outputs.backend == 'true' || needs.check_changes.outputs.backend == true
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_KEY }}

      - name: Deploy Backend DigitalOcean
        run: |
          doctl apps create-deployment --app ${{ secrets.DO_BACKEND_APP_ID }}

  deploy_frontend:
    runs-on: ubuntu-latest
    needs: check_changes
    if: needs.check_changes.outputs.frontend == 'true' || needs.check_changes.outputs.frontend == true
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_KEY }}

      - name: Deploy Frontend DigitalOcean
        run: |
          doctl apps create-deployment --app ${{ secrets.DO_FRONTEND_APP_ID }}
